version: "3"
services:
  backend:
    container_name: backend/springboot
    build: ./backend
    image: back_image:0.0
    ports:
      - "8080:8080"
    networks:
      - backend_frontend

  frontend:
    container_name: frontend
    build: ./frontend
    image: front_image:0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
    networks:
      - backend_frontend

networks:
  backend_frontend:
    driver: bridge
