version: "3"
services:
  backend:
    container_name: springboot
    build: ./backend/springboot
    image: back_image:0.0
    ports:
      - "8080:8080"
    networks:
      - backend_frontend

  frontend:
    container_name: frontend
    build: ./frontend
    image: front_image:0.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/lib/letsencrypt:/var/lib/letsencrypt
      - /home/ubuntu/nginx/conf.d:/etc/nginx/conf.d
      - /home/ubuntu/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /home/ubuntu/nginx/dist:/usr/share/nginx/html

    networks:
      - backend_frontend

networks:
  backend_frontend:
    driver: bridge
