spring:
  datasource:
    url: jdbc:mysql://savior.c7cmcuk2k97d.ap-northeast-2.rds.amazonaws.com/savior?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver



web:
  cors:
    allowed-origins=*:

server:
  servlet:
    context-path: /api

