spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://savior.c7cmcuk2k97d.ap-northeast-2.rds.amazonaws.com/savior?useSSL=false&serverTimezone=UTC
    username: root
    password: root1234
  #    hikari:
  #      pool-name: jpa-hikari-pool
  #      maximum-pool-size: 5
  #      jdbc-url: ${spring.datasource.url}
  #      username: ${spring.datasource.username}
  #      password: ${spring.datasource.password}
  #      driver-class-name: ${spring.datasource.driver-class-name}
  #      data-source-properties:
  #        rewriteBatchedStatements: true

  # JPA ??
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        hbm2ddl.import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        default_batch_fetch_size: ${chunkSize:100}
        jdbc.batch_size: 20
        order_inserts: true
        order_updates: true
        format_sql: true
        use-new-id-generator-mappings: false
        naming:
          physical-strategy: org.hibernate.boot.model.naming      .PhysicalNamingStrategyStandardImp

  # Security OAuth
  security:
    oauth2.client:
      registration:
        kakao:
          clientId: '2b3e53a89d2794b4afa3cbed27c2ad30'
          clientSecret: 'GGxnBUprx4NVmo84JKIzuaLvhIS9Itxf'
          clientAuthenticationMethod: client_secret_post
          authorizationGrantType: authorization_code
          redirectUri: "https://j10d109.p.ssafy.io/{action}/oauth2/code/{registrationId}"
          scope:
            - profile_nickname
            - profile_images
          #            - account_email
          #            - age_range
          #            - gender
          #            - birthday
          clientName: Kakao
      # Provider 설정
      provider:
        kakao:
          authorizationUri: https://kauth.kakao.com/oauth/authorize
          tokenUri: https://kauth.kakao.com/oauth/token
          userInfoUri: https://kapi.kakao.com/v2/user/me
          userNameAttribute: id

# cors 설정
cors:
  allowed-origins: 'https://j10d109.p.ssafy.io'
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: '*'
  max-age: 3600

# jwt secret key 설정
jwt.secret: '8sknjlO3NPTBqo319DHLNqsQAfRJEdKsETOds'

web:
  cors:
    allowed-origins=*:

# 토큰 관련 secret Key 및 RedirectUri 설정
app:
  auth:
    tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    tokenExpiry: 432000000
    refreshTokenExpiry: 604800000
  oauth2:
    authorizedRedirectUris:
      - https://j10d109.p.ssafy.io/oauth/kakao/callback
server:
  servlet:
    context-path: /api